"""
Generate pokebot/gen2_gender.py — the per-species gender ratios.

Gen 2 does not store gender on a Pokemon. It derives it at display
time from the Attack DV against the species' gender ratio byte, which
lives in the ROM's base-stats table:

    female  if  (Attack DV * 16) < gender_ratio

Rather than hunt that table in the emulated ROM, the ratios are taken
once from PokeAPI's ``gender_rate`` (chance of being female, in
eighths) and converted:

    -1  genderless        -> 255
     0  always male       ->   0
     8  always female     -> 254
     n  n/8 female        -> n*32 - 1

That conversion is exact for the Game Boy rule. With ratio 127 a
Pokemon is female when Atk*16 < 127, i.e. Atk <= 7 — 8 of 16 values,
50%. Ratio 31 gives Atk <= 1, 2 of 16, 12.5%. And so on.

    python scripts/gen_gender_table.py

Writes the module, which is committed so users never need the network.
"""
from __future__ import annotations

import json
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "pokebot" / "gen2_gender.py"

MAX_SPECIES = 251          # Celebi
API = "https://pokeapi.co/api/v2/pokemon-species/{sid}/"


def ratio_byte(gender_rate: int) -> int:
    """PokeAPI gender_rate -> Game Boy gender ratio byte."""
    if gender_rate < 0:
        return 255          # genderless
    if gender_rate == 0:
        return 0            # always male
    if gender_rate >= 8:
        return 254          # always female
    return gender_rate * 32 - 1


def fetch(sid: int) -> tuple:
    req = urllib.request.Request(
        API.format(sid=sid), headers={"User-Agent": "pokebot-3ds/0.1"})
    with urllib.request.urlopen(req, timeout=20) as resp:
        data = json.load(resp)
    return sid, int(data["gender_rate"]), data["name"]


def main() -> int:
    print(f"fetching gender rates for species 1..{MAX_SPECIES} …")
    rows: dict[int, tuple] = {}
    with ThreadPoolExecutor(max_workers=8) as pool:
        for sid, rate, name in pool.map(fetch, range(1, MAX_SPECIES + 1)):
            rows[sid] = (rate, name)
            if sid % 50 == 0:
                print(f"  {sid}/{MAX_SPECIES}")

    lines = [
        '"""',
        "Per-species gender ratios for Generation II.",
        "",
        "AUTO-GENERATED by scripts/gen_gender_table.py — do not edit by hand.",
        "",
        "Gen 2 stores no gender on a Pokemon; it is derived from the Attack",
        "DV against these ratio bytes:",
        "",
        "    female  if  (Attack DV * 16) < ratio",
        "",
        "255 means genderless, 0 always male, 254 always female.",
        '"""',
        "",
        "GENDER_RATIOS = {",
    ]
    for sid in sorted(rows):
        rate, name = rows[sid]
        lines.append(f"    {sid}: {ratio_byte(rate)},"
                     f"  # {name}")
    lines.append("}")
    lines.append("")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(rows)} species)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
